### DISCUSSION TITLE
Readings are too large

### DISCUSSION THREAD

**Discussion by dinki** [allangood/rtlamr2mqtt#135] [Q&A] [answered]
Me again.  I've successfully configured my new meter but the readings appear to be too large.  I am using aa Itron SK9C1A-3 and it's configured like this:

```
meters:
  - id: XXXXXXXX
    protocol: scm
    name: Electric_Meter
    #format: "######.###"
    unit_of_measurement: "KWh"
    icon: mdi:gauge
    device_class: energy
```

My last two hours have read 528kW and 453kW.  I'd expect these readings to be more in the order of 5.28kW and 4.53kW.  I thought this might be an issue where the unit of measure was actually Wh but that would make the readings too small, right?  The meter does say that it is an 'Itron Watthour Meter', but I think .5kW and .4kW for the last two hours is too low as my central air conditioning has been running a lot.  I checked yesterday's usage and it was around 4-5kW per hour as read with the old meter.

Can the format line be used to force these readings to be reading/100 or should I create a template sensor in HA to do this?  I'm just making guesses
