### DISCUSSION TITLE
keep getting "IsADirectoryError: [Errno 21] Is a directory: '/etc/rtlamr2mqtt.yaml'"

### DISCUSSION THREAD

**Discussion by ljmerza** [allangood/rtlamr2mqtt#160] [Q&A] [answered]
my docker compose config:

```
rtlamr:
    container_name: rtlamr
    image: allangood/rtlamr2mqtt
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    volumes:
      - /.volumes/rtlamr/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro
      - ./volumes/rtlamr/data:/var/lib/rtlamr2mqtt
```

the `/.volumes/rtlamr/rtlamr2mqtt.yaml` is a file ive edited but docker keeps seeing it as a directory.
