### DISCUSSION TITLE
Specifying device in docker-compose

### DISCUSSION THREAD

**Discussion by dinki** [allangood/rtlamr2mqtt#162] [Q&A]
Hello again.  I'm running into an issue where I THINK rtlamr2mqtt is trying to use a device that I am already using for rtl433 docker container.  All was fine for a long while until I had a reboot and I've had issues ever since.

I have two rtlsdr dongles connected.  They are identical brand/model and show up as   '/dev/bus/usb/001/003'    and '/dev/bus/usb/002/003'

My docker-compose file looks like this for these pieces:

```
  rtl433:
    container_name: rtl433
    image: hertzg/rtl_433:latest
    restart: unless-stopped
    depends_on:
      - mqtt
      - rtlamr
    devices:
      - '/dev/bus/usb/001/003'      
      #- '/dev/bus/usb/002/003'
    command:
      - '-Fmqtt://192.168.0.25:1883,retain=1'
  rtlamr:
    container_name: rtlamr2mqtt
    image: allangood/rtlamr2mqtt
    restart: unless-stopped
    devices:
      - /dev/bus/usb
    volumes:
      - /sharedfolders/appdata/rtlamr2mqtt/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro
      - /sharedfolders/appdata/rtlamr2mqtt/data:/var/lib/rtlamr2mqtt
```

I'm trying to make sure that one device is assigned to each container.  I did try setting the rtlamr2mqtt device in a similar way to rtl433 container device definition using the 002/003 device but it did not seem to work.  Can someone tell me how I can force each container to use separate devices?

Please excuse my ignorance on this.  Any help is most appreciated!
