### DISCUSSION TITLE
Unable to save configuration

### DISCUSSION THREAD

**Discussion by jeffdeal** [allangood/rtlamr2mqtt#276] [Q&A]
I've updated an operational installation today, and when I try to start the add-on am getting the following error:

value must be one of ['critical', 'debug', 'info', 'none', 'warning'].

I looked at the config, and the verbosity was set to "normal" which is not in this list. But when I try to change it to one of the other defined values, I can't save it and get the following message:

Failed to save add-on configuration, does not match regular expression (^0|^(0[xX])?[A-Fa-f0-9]+:(0[xX])?[A-Fa-f0-9]+$). Got {'general': {'sleep_for': 300, 'verbosity': 'info', 'device_id': 'single', 'rtltcp_host': '127.0.0.1:1234', 'listen_only': False, 'tickle_rtl_tcp': False}, 'mqtt': {'host': '127.0.0.1', 'port': 1883, 'ha_autodiscovery_topic': 'homeassistant', 'ha_status_topic': 'hass/status', 'base_topic': 'rtlamr', 'ha_autodiscovery': True, 'tls_enabled': False}, 'custom_parameters': {'rtltcp': '-s 2048000', 'rtlamr': '-unique=true'}, 'meters': [{'id': 1704641, 'protocol': 'scm', 'name': '18_gas_meter', 'for...

I can't tell what is wrong. Does anybody have ideas?  

[RTLConfig.txt](https://github.com/user-attachments/files/20555275/RTLConfig.txt)

**Comment by allangood** [comment]
Try to use the latest config file format:
https://github.com/allangood/rtlamr2mqtt/blob/main/rtlamr2mqtt-addon/app/rtlamr2mqtt.yaml

```
general:
  sleep_for: 300
  verbosity: info

mqtt:
  host: core-mosquitto
  port: 1883
  user: <USER HERE>
  password: <PASSWORD HERE>
  ha_autodiscovery_topic: homeassistant
  ha_status_topic: hass/status
  base_topic: rtlamr
  ha_autodiscovery: true
  tls_enabled: false

meters:
  - id: xxxxxxxx
    protocol: scm
    name: 18_gas_meter
    format: "#####.##"
    unit_of_measurement: ft³
    icon: mdi:gas_canister
    device_class: gas
    state_class: total_increasing
  - id: xxxxxxxx
    protocol: r900
    name: 18_water_meter
    format: "######.#"
    icon: mdi:gas_canister
    unit_of_measurement: gal
    device_class: water
    state_class: total_increasing
  - id: xxxxxxxx
    protocol: r900
    name: 16_water_meter
    format: "######.#"
    icon: mdi:gas_canister
    unit_of_measurement: gal
    device_class: water
    state_class: total_increasing
```
