### DISCUSSION TITLE
Welcome to rtlamr2mqtt Discussions!

### DISCUSSION THREAD

**Discussion by allangood** [allangood/rtlamr2mqtt#60] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by DallasJWilm** [comment]
Hello!  I'm Dallas.  To answer what I do with this community: I don't do anything :) and am humble to the bright minds of github (and am proud to make it as far as I have so far).  I am just trying to figure out how to use this great work!  I am excited to see there might be a way to get my gas and water meter data into home assistant.  

I am afraid I am stuck.  When attempting to run: 

"sudo docker run -ti -e RTL_MSGTYPE="all" --device=/dev/bus/usb:/dev/bus/usb allangood/rtlamr2mqtt"

and after creating the .yaml config file at /etc/rtlamr2mqtt.yaml I am getting the error:

Configuration file cannot be found at "/etc/rtlamr2mqtt.yaml"

I found this post: https://githubmemory.com/index.php/repo/allangood/rtlamr2mqtt/issues/52 but I am afraid I don't really understand the post by jcollas.  In addition, after doing some Googling, I found what I think is the docker container, but I don't see anything explicitly related to the rtlamr2mqtt docker file.

Any help would be much appreciated!

Dallas

**Reply by allangood** [reply]
Hi Dallas,

That command is to run the container in ***LISTEN ALL*** mode, this is intended to be used only to help to discover a meter ID, not to run in the long term. I should put that section in the bottom of the README file as it causes A LOT of confusion, not only with you. :)

Best way to run the container is using compose, but if you want to run using the command like, you should use this way:
```
docker run -d --name rtlamr2mqtt --device=/dev/bus/usb:/dev/bus/usb -v /etc/rtlamr2mqtt.yaml:/etc/rtlamr2mqtt.yaml:ro -v /var/lib/rtlamr2mqtt:/var/lib/rtlamr2mqtt allangood/rtlamr2mqtt
```

Regards

**Reply by DallasJWilm** [reply]
Awesome, thanks!  I make more progress now, no error message.  I tried the command you gave.  It returned a hex string, then I could see it running using docker ps.  However, it disappeared from that list and when I reuse that command, it says it is already in use by another container.  I will see if I can learn how to run the container using compose.

Dallas

**Reply by allangood** [reply]
You have to stop and remove your old container before running a new one with same name:
```
docker stop rtlamr2mqtt
docker rm rtlamr2mqtt
```

Regards

**Reply by DallasJWilm** [reply]
Thanks for your help.  So, I looked at what I think is needed to run using docker-compose.  I created a directory with docker-compose.yml with your docker compose configuration in it.  Cd'ed to it in terminal.  Tried to run it using docker-compose up.  Starts working but then I get the following:

```
rtlamr2mqtt | Traceback (most recent call last):
rtlamr2mqtt |   File "/usr/bin/rtlamr2mqtt.py", line 257, in <module>
rtlamr2mqtt |     config = load_config(sys.argv)
rtlamr2mqtt |   File "/usr/bin/rtlamr2mqtt.py", line 130, in load_config
rtlamr2mqtt |     return load_yaml_config(config_path)
rtlamr2mqtt |   File "/usr/bin/rtlamr2mqtt.py", line 140, in load_yaml_config
rtlamr2mqtt |     return yaml.safe_load(config_file)
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
rtlamr2mqtt |     return load(stream, SafeLoader)
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
rtlamr2mqtt |     return loader.get_single_data()
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
rtlamr2mqtt |     node = self.get_single_node()
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
rtlamr2mqtt |     document = self.compose_document()
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
rtlamr2mqtt |     node = self.compose_node(None, None)
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
rtlamr2mqtt |     node = self.compose_mapping_node(anchor)
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
rtlamr2mqtt |     item_value = self.compose_node(node, item_key)
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 82, in compose_node
rtlamr2mqtt |     node = self.compose_sequence_node(anchor)
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
rtlamr2mqtt |     while not self.check_event(SequenceEndEvent):
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
rtlamr2mqtt |     self.current_event = self.state()
rtlamr2mqtt |   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 392, in parse_block_sequence_entry
rtlamr2mqtt |     raise ParserError("while parsing a block collection", self.marks[-1],
rtlamr2mqtt | yaml.parser.ParserError: while parsing a block collection
rtlamr2mqtt |   in "/etc/rtlamr2mqtt.yaml", line 37, column 3
rtlamr2mqtt | expected <block end>, but found '<block sequence start>'
rtlamr2mqtt |   in "/etc/rtlamr2mqtt.yaml", line 52, column 4
```


Honestly, I am not even sure what this is telling me, all i can say is the last 6 lines don't look good (with my assumption being the lines above the last 6 lines are just to provide context?).  The last 4 look like they are related to the .yaml file.. but I believe I formatted exactly the same as you did in your example file.  

Then, I have no idea what the two lines, 5th and 6th from the bottom mean.  

Below is what is in my yaml file.

```
# (Optional section)
general:
  # Sleep for this amount of seconds after one successful of every meter
  # Set this to 0 (default) to disable it
  sleep_for: 0
  # Set the verbosity level. It can be debug or info
  verbosity: debug

# (Required section)
# MQTT configuration
mqtt:
  # MQTT host name or IP address
  host: 127.0.0.1
  # MQTT user name if you have, remove if you don't use authentication
  user: 
  # MQTT user password if you use one, remove if you don't use authentication
  password: 
  # Whether to use Home Assistant auto-discovery feature or not
  ha_autodiscovery: true
  # Home Assistant auto-discovery topic
  ha_autodiscovery_topic: homeassistant

# (Optional)
# This entire section is optional.
# If you don't need any custom parameter, don't use it.
# ***DO NOT ADD -msgtype, -filterid nor -protocol parameters here***
custom_parameters:
  # Documentation for rtl_tcp: https://osmocom.org/projects/rtl-sdr/wiki/Rtl-sdr
  rtltcp: "-s 2048000"
  # Documentation for rtlamr: https://github.com/bemasher/rtlamr/wiki/Configuration
  rtlamr: "-unique=true -symbollength=32"

# (Required section)
# Here is the place to define your meters
meters:
    # The ID of your meter
  - id: 1568947908
    # The protocol
    protocol: r900
    # A nice name to show on your Home Assistant/Node Red
    name: Outside_Water_Meter
    # A number format to be used for your meter
    format: "#######.#"
    # A measurement unit to be used by Home Assistant
    unit_of_measurement: "gal"
    # An icon to be used by Home Assistant
    icon: mdi:gauge
  - id: 1568515126
    protocol: r900
    name: Inside_Water_Meter
    unit_of_measurement: "gal"
   - id: 76774025
    # The protocol
    protocol: scm+
    # A nice name to show on your Home Assistant/Node Red
    name: Gas_Meter
    # A number format to be used for your meter
    format: "######"
    # A measurement unit to be used by Home Assistant
    unit_of_measurement: "cubic feet x10"
    # An icon to be used by Home Assistant
    icon: mdi:gauge
```
