### DISCUSSION TITLE
General help

### DISCUSSION THREAD

**Discussion by allangood** [allangood/rtlamr2mqtt#65] [General]
Please, use this thread for general support questions.

Thank you!

**Comment by markwoodward86** [comment]
Hi there!

I just updated to the latest 1.5.4 but lost my sensors in MQTT. The meters are still being read in rtlamr according to the logs and still being sent to MQTT but the entities show 'unavailable'. Tried uninstalling MQTT and resetting everything up but now entities show up at all (with both auto discovery and manually). 

Any ideas?

log output in attachment 
[rtlamr error.log](https://github.com/allangood/rtlamr2mqtt/files/7857433/rtlamr.error.log)

**Reply by allangood** [reply]
it is a bug introduced by the device_class feature. I am working on it to fix ASAP.
Thank you for reporting.

**Reply by allangood** [reply]
I just pushed #70 and the correction will be available shortly

**Reply by markwoodward86** [reply]
Thank you very much for your quick turnaround on this! Installed and working.

Much appreciated.

**Reply by allangood** [reply]
Thank you for reporting the problem!
I am still working in a better way to test everything before going to production.

**Comment by eCyclops** [comment]
I have set up using the addon and it seems to work correctly. 
```
meters:
  - id: <obfuscated>
    protocol: scm
    name: house_electric_meter
    format: "#####.##"
    unit_of_measurement: kWh
    icon: mdi:gauge
    device_class: energy
    state_class: total_increasing
    native_unit_of_measurement: kWh
    native_value: decimal.Decimal
```

However, although I can see the correct meter reading as "state" of my meter ID using MQTT Explorer, I can't seem to get Home Assistant to notice it.

I believe the meter config is working to some degree, as I was able to change the state (from the "Consumption" field in the scm) format from three digits to the right of the decimal to two.

I don't see any errors, just nothing showing up in Energy. The energy dashboard suggests this page: https://www.home-assistant.io/more-info/statistics/
