### DISCUSSION TITLE
Unit of measurement conversions?

### DISCUSSION THREAD

**Discussion by drmulligan** [allangood/rtlamr2mqtt#68] [Ideas]
Home Assistant Energy requires metric units of measurement.  I have provided HA with a template sensor to convert the units and add the device class.   This works for me.  I am just wondering if new users would find it better to have rtlamr2mqtt provide an option to convert units or maybe just an example or mention in the documentation would be enough.

**Comment by allangood** [comment]
Adding this as a feature would open to many requests down the road, there are many conversions possible...
I think this is something that should be addressed by a more high level instance, like Home Assistant.

Could you provide your configuration sample? I can add it to the README file.

**Comment by stu1811** [comment]
This converts from ft^3 to m^3

```
template:
  - sensor:
      - name: gas_meter_metric
        device_class: gas
        state_class: total_increasing
        unit_of_measurement: m³
        state: "{{ (float(states('sensor.gas_meter')) * 0.028317) | round(3) }}"
```
