### ISSUE TITLE
NameError: name 'tls' is not defined

### ISSUE THREAD

**Issue by ProConvenience** [allangood/rtlamr2mqtt#105]
I just installed the add-on in my Home Assistant OS instance and I'm getting this error: 
```
[2022-04-06 17:49:53] Fetching default MQTT configuration from http://supervisor/services/mqtt
Traceback (most recent call last):
  File "/usr/bin/rtlamr2mqtt.py", line 327, in <module>
    mqtt_sender = MqttSender(host, port, user, password, tls)
NameError: name 'tls' is not defined
```

I don't believe it's related to mqtt since the Mosquitto add-on has been working fine for months.
It could be related to the most recent update (1.7.0) and it's just a coincidence that I installed this add-on for the first time.
It could also be related to me not having the `tls_cert` and `tls_keyfile` files.

Here's my Configuration (almost default):
```
general:
  sleep_for: 300
  verbosity: debug
  tickle_rtl_tcp: false
  usb_reset: '005:002'
mqtt:
  ha_autodiscovery: true
  ha_autodiscovery_topic: homeassistant
  tls_ca: /etc/ssl/certs/ca-certificates.crt
  tls_cert: /etc/ssl/my_self_signed_cert.crt
  tls_keyfile: /etc/ssl/my_self_signed_cert_key.key
  tls_insecure: true
custom_parameters:
  rtltcp: '-s 2048000'
  rtlamr: '-unique=true'
meters:
  - id: 1042xxxx
    protocol: scm
    name: gas_meter
    format: '####.###'
    unit_of_measurement: m³
    icon: mdi:gas_canister
    device_class: gas
```

Possibly a separate issue, but when I try to remove `tls_cert` or `tls_keyfile` when I restart the add-on those lines come back. Also, when I try to get rid of `custom_parameters`, I get an error preventing me from saving.

I'm happy to help diagnose and to provide whatever's needed to figure this out.
