### ISSUE TITLE
Supervisor Warning - Unknown option 'port'

### ISSUE THREAD

**Issue by stu1811** [allangood/rtlamr2mqtt#159]
Home Assistant 2022.9.6
Supervisor 2022.09.1
Frontend 20220907.2 - latest

`WARNING (MainThread) [supervisor.addons.options] Unknown option 'port' for rtlamr2mqtt (6713e36e_rtlamr2mqtt)`

```
general:
  sleep_for: 60
  verbosity: debug
  listen_only: false
  tickle_rtl_tcp: false
  device_id: single
mqtt:
  ha_autodiscovery: true
  ha_autodiscovery_topic: homeassistant
  base_topic: rtlamr
  tls_enabled: false
  host: core-mosquitto
  port: 1883
  user: "!secrets mqtt_user"
  password: "!secrets mqtt_pass"
custom_parameters:
  rtltcp: "-s 2048000"
  rtlamr: "-unique=true"
meters:
  - id: XXXXX
    protocol: r900
    name: water_meter
    format: "#######.#"
    unit_of_measurement: ft³
    icon: mdi:water-pump
  - id: XXXXXX
    protocol: scm
    name: gas_meter
    format: "####.##"
    unit_of_measurement: ft³
    icon: mdi:gas-cylinder
```

**Comment by sargonas** [comment]
Are you running on the default port? If so try removing the port line. I don't use it myself and am on default.. I did try adding the line to my config with the default port set and got the same error, fwiw.

**Comment by sargonas** [comment]
Actually I think this might be because "port" is not declared inthe config.yaml that HA uses as a vaidator?

try this fork of mine: https://github.com/sargonas/rtlamr2mqtt
I added a port declaration to see if that makes a difference for you. I would test it locally but I am on a plane atm, but will try later tonight myself if I haven't heard back by then.

**Comment by blandry3** [comment]
Similar issue here. I'm trying to use port 11298, but the log says 👍 

`[2022-10-07 16:29:01]  > port => 1883`

and

`[2022-10-07 16:29:06] Unknown exception connecting to MQTT broker: timed out`

**Comment by stu1811** [comment]
> Actually I think this might be because "port" is not declared in the config.yaml that is used as a validator?
> 
> try this fork of mine: https://github.com/sargonas/rtlamr2mqtt (or change the config.yaml locally) it has one simply change of adding `port: str?` under `host: str?` in the rtlamr2mqtt-addon/config.yaml file
> 
> I would test it locally but I am on a plane atm, but will try later tonight myself if I haven't heard back by then.

Here is my mqtt config:
```
mqtt:
  ha_autodiscovery: true
  ha_autodiscovery_topic: homeassistant
  base_topic: rtlamr
  tls_enabled: false
  host: core-mosquitto
  port: 1883
  user: "!secrets mqtt_user"
  password: "!secrets mqtt_pass"
```

I tried modified `addons/git/6713e36e/rtlamr2mqtt-addon/config.yaml` per your suggestion. Restarting the addon and rebuilding and then restarting didn't stop the warnings in Supervisor. Do I need to do anything else to force the container to update?

The update...

```
  mqtt:
    host: str?
    port: str?
    user: str?
    password: str?
    ha_autodiscovery: bool?
    ha_autodiscovery_topic: str?
    base_topic: str
    tls_enabled: bool?
    tls_ca: str?
    tls_cert: str?
    tls_keyfile: str?
    tls_insecure: bool?
```
