### ISSUE TITLE
Allow Meter ID to be stored in secrets.yaml

### ISSUE THREAD

**Issue by ayourk** [allangood/rtlamr2mqtt#178]
It would be great to be able to do something like the following in secrets,yaml and then use that in the config to hide the meter IDs in the main config.

--- secrets.yaml ---
meter_elec: 10528282
meter_gas: 52212210
meter_water: 3223125100
--- --- --- --- ---

The numbers above are random numbers I created in the moment and are not reflective of an exact meter ID; they are used as examples only.
```--- meters config ---
- id: !secret meter_elec 
  protocol: scm
  name: meter_electricity
  format: "#####.##"
  unit_of_measurement: kWh
  icon: mdi:lightning-bolt
  device_class: energy
  state_class: total_increasing
  filters:
    - multiply: 0.01
- id: !secret meter_gas
  protocol: scm
  name: meter_gas
  format: "####.###"
  unit_of_measurement: ft³
  icon: mdi:gas-meter
  device_class: gas
  state_class: total_increasing
  filters:
    - multiply: 0.001
- id: !secret meter_water
  protocol: r900
  name: meter_water
  format: "#######.#"
  unit_of_measurement: gal
  icon: mdi:water
  device_class: water
  state_class: total_increasing
  filters:
    - multiply: 0.1
```
--- --- --- --- --- ---

Please note:  If you want to add Gas or Water to the Energy Dashboard, you MUST change the units to m³.  Once added to the energy dashboard, the units can be changed back.

**Comment by onedr0p** [comment]
Another improvement to this would to also be able to support injecting env like this

```yaml
- id: !env METER_ID
  protocol: r900
  name: meter_water
  format: "#######.#"
  unit_of_measurement: gal
  icon: mdi:water
  device_class: water
  state_class: total_increasing
  filters:
    - multiply: 0.1
```
