### ISSUE TITLE
Duplicate Entities

### ISSUE THREAD

**Issue by robertscheib** [allangood/rtlamr2mqtt#201]
I'm trying to integrate my water meter into the Energy Dashboard but I am running into some issues. It appears that my system is seeing two water meter entities, sensor.water_meter_2 and sensor.water_meter

My primary dashboard is displaying my usage from sensor.water_meter_2 correctly, but the Energy Dashboard is only seeing sensor.water_meter with no usage data. During my troubleshooting I removed all rtlamr2mqtt and mqtt components and rebuilt everything, before doing this I was seeing sensor.water_meter_3 and sensor.water_meter but the Energy Dashaobrd wouldn't see either, so I am making progress here.

Any help is appreciated? Below is my code, let me know if I need to provide anything else.

Configuration.yaml
```
mqtt:
  sensor:
    - name: "Water Meter"
      device_class: water
      state_class: total_increasing
      unique_id: "water_meter"
      state_topic: "rtlamr/water_meter/state"
      unit_of_measurement: "gal"
```
rtlamr2mqtt Configuration:
```
general:
  sleep_for: 300
  verbosity: debug
  listen_only: false
  tickle_rtl_tcp: false
  device_id: single
mqtt:
  ha_autodiscovery: true
  ha_autodiscovery_topic: homeassistant
  base_topic: rtlamr
  tls_enabled: false
  host: ###.###.###.###
  port: 1883
  user: XXXXXXX
  password: XXXXXXX
custom_parameters:
  rtltcp: "-s 2048000"
  rtlamr: "-unique=true"
meters:
  - id: XXXXXXXXXX
    protocol: r900
    name: water_meter
    format: "######.#"
    unit_of_measurement: Gal
    icon: mdi:water
```
