### ISSUE TITLE
[BUG] Home assistant is unhappy with 127.0.0.1

### ISSUE THREAD

**Issue by lubarb** [allangood/rtlamr2mqtt#281]
**Describe the bug**
After installation, the home assistant add-on fails on startup with: CRITICAL:Failed to connect to MQTT broker: [Errno 111] Connection refused

**To Reproduce**
Install and check the log. Replacing the 127.0.0.1 in my MQTT configuration section with the name of my homeassistant server fixes the problem.

I am using this Configuration (after the change to make it work):
```
general:
  sleep_for: 60
  verbosity: info
  device_id: "0"
  rtltcp_host: 127.0.0.1:1234
mqtt:
  host: homeassistant     _ It installs 127.0.0.1 here, and gives the error. Changing to this (my server name) works_
  port: 1883
  ha_autodiscovery_topic: homeassistant
  ha_status_topic: hass/status
  base_topic: rtlamr
custom_parameters:
  rtltcp: "-s 2048000"
  rtlamr: "-unique=true"
meters:
  - id: 22222222
    protocol: r900
    name: my_energy_meter
    format: "######.###"
    device_class: energy
```

**Expected behavior**
I expected it not to crash

**Screenshots or logs**
[2025-06-02 21:05:37,997] INFO:Starting rtlamr2mqtt 2025.6.1
[2025-06-02 21:05:37,997] INFO:Config loaded successfully
[2025-06-02 21:05:37,997] INFO:Connecting to MQTT broker at 127.0.0.1:1883
[2025-06-02 21:05:37,999] CRITICAL:Failed to connect to MQTT broker: [Errno 111] Connection refused

vs

[2025-06-02 21:07:08,985] INFO:Starting rtlamr2mqtt 2025.6.1
[2025-06-02 21:07:08,985] INFO:Config loaded successfully
[2025-06-02 21:07:08,986] INFO:Connecting to MQTT broker at homeassistant:1883
[2025-06-02 21:07:08,989] INFO:Subscribing to hass/status
[2025-06-02 21:07:08,989] INFO:Publishing to homeassistant/device/22222222/config: {"device": {"identifiers": "meter_22222222", "name": "my_energy_meter", "manufacturer": "RTLAMR2MQTT", "model": "Smart Meter", "sw_version": "1.0", "serial_number": 22222222, "hw_version": "1.0"}, "origin": {"name": "2mqtt", "sw_version": "2025.6.1", "support_url": "https://github.com/allangood/rtlamr2mqtt"}, "components": {"22222222_reading": {"platform": "sensor", "name": "Reading", "value_template": "{{ value_json.reading|float }}", "json_attributes_topic": "rtlamr/22222222/attributes", "unique_id": "22222222_reading", "protocol": "r900", "format": "######.###", "device_class": "energy"}, "22222222_lastseen": {"platform": "sensor", "name": "Last Seen", "device_class": "date", "value_template": "{{ value_json.lastseen }}", "unique_id": "22222222_lastseen"}}, "state_topic": "rtlamr/22222222/state", "availability_topic": "rtlamr/status", "qos": 1}
[2025-06-02 21:07:09,990] INFO:Publishing to rtlamr/status: online
[2025-06-02 21:07:10,040] DEBUG:Reseting USB device: 001:007
[2025-06-02 21:07:10,211] INFO:Starting RTL_TCP using "rtl_tcp -s 2048000 -d 0"
Found 2 device(s):
  0:  RTLSDRBlog, Blog V4, SN: 00000001
  1:  Realtek, RTL2838UHIDIR, SN: 00000001
Using device 0: Generic RTL2832U OEM
Found Rafael Micro R828D tuner
RTL-SDR Blog V4 Detected
Tuned to 100000000 Hz.

**Version Information:**
Installation method: Home Assistant OS
Core: 2025.5.2
Supervisor: 2025.05.3
Operating System: 15.2
Frontend: 20250516.0

**Additional context**
In case it makes a difference, I'm running on a Beelink Intel mini pc rather than a pi based system.
